// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as OrtaVox from "../../../index.js";

export declare namespace AgentsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Agent management endpoints
 */
export class AgentsClient {
    protected readonly _options: AgentsClient.Options;

    constructor(options: AgentsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Retrieve a paginated list of all AI voice agents configured for the authenticated organization.
     *
     * @param {OrtaVox.ListAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.list()
     */
    public list(
        request: OrtaVox.ListAgentsRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: OrtaVox.ListAgentsRequest = {},
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/agents",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OrtaVoxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling GET /v1/agents.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new AI agent with specified configuration. Requires authentication via Clerk JWT or API key.
     *
     * @param {OrtaVox.CreateAgent} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.BadRequestError}
     * @throws {@link OrtaVox.UnauthorizedError}
     *
     * @example
     *     await client.agents.create({
     *         name: "Support Agent",
     *         transcriber: {
     *             provider: "deepgram",
     *             model: "nova-3",
     *             language: "en"
     *         },
     *         model: {
     *             provider: "openai",
     *             model: "gpt-4o-mini",
     *             system_prompt: "You are a helpful AI assistant",
     *             temperature: 1.1,
     *             max_tokens: 1.1
     *         },
     *         voice: {
     *             provider: "elevenlabs",
     *             voice_id: "dqzVFKHwZvR9YMQoFM67",
     *             model: "eleven_turbo_v2_5"
     *         }
     *     })
     */
    public create(
        request: OrtaVox.CreateAgent,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.AgentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: OrtaVox.CreateAgent,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.AgentResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/agents",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OrtaVox.AgentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OrtaVox.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling POST /v1/agents.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a specific agent
     *
     * @param {OrtaVox.GetAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.agents.get({
     *         agentId: "agentId"
     *     })
     */
    public get(
        request: OrtaVox.GetAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: OrtaVox.GetAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { agentId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/agents/${core.url.encodePathParam(agentId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling GET /v1/agents/{agentId}.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete an agent by ID
     *
     * @param {OrtaVox.DeleteAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agents.delete({
     *         agentId: "agentId"
     *     })
     */
    public delete(
        request: OrtaVox.DeleteAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: OrtaVox.DeleteAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { agentId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/agents/${core.url.encodePathParam(agentId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OrtaVoxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling DELETE /v1/agents/{agentId}.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Partially update agent configuration. Only provided fields will be updated.
     *
     * @param {OrtaVox.UpdateAgentsRequest} request
     * @param {AgentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.agents.update({
     *         agentId: "agentId",
     *         body: {
     *             name: "Support Agent",
     *             transcriber: {
     *                 provider: "deepgram",
     *                 model: "nova-3",
     *                 language: "en"
     *             },
     *             model: {
     *                 provider: "openai",
     *                 model: "gpt-4o-mini",
     *                 system_prompt: "You are a helpful AI assistant",
     *                 temperature: 1.1,
     *                 max_tokens: 1.1
     *             },
     *             voice: {
     *                 provider: "elevenlabs",
     *                 voice_id: "dqzVFKHwZvR9YMQoFM67",
     *                 model: "eleven_turbo_v2_5"
     *             }
     *         }
     *     })
     */
    public update(
        request: OrtaVox.UpdateAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: OrtaVox.UpdateAgentsRequest,
        requestOptions?: AgentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { agentId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/agents/${core.url.encodePathParam(agentId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling PATCH /v1/agents/{agentId}.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
