// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "API request",
 *         type: "end_call"
 *     }
 */
export interface CreateTool {
    /** Tool name */
    name: string;
    /** Tool type */
    type: CreateTool.Type;
    /** Tool description (optional, auto-generated if not provided) */
    description?: string;
    /** API endpoint URL (required for api type) */
    url?: string;
    /** HTTP method (required for api type) */
    method?: CreateTool.Method;
    /** HTTP headers for api type */
    headers?: Record<string, unknown>;
    /** JSON Schema for tool parameters */
    parameters?: CreateTool.Parameters;
}

export namespace CreateTool {
    /** Tool type */
    export const Type = {
        EndCall: "end_call",
        Api: "api",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** HTTP method (required for api type) */
    export const Method = {
        Get: "GET",
        Post: "POST",
        Put: "PUT",
        Delete: "DELETE",
        Patch: "PATCH",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];

    /**
     * JSON Schema for tool parameters
     */
    export interface Parameters {
        type?: string;
        properties?: Record<string, unknown>;
        required?: string[];
    }
}
