// This file was auto-generated by Fern from our API Definition.

import type * as OrtaVox from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListToolsRequest {
    /** Filter by tool type */
    type?: OrtaVox.ListToolsRequestType;
}
