// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateTool {
    /** Tool ID */
    id: string;
    name?: string;
    description?: string;
    goodbye_message?: string;
    url?: string;
    method?: UpdateTool.Method;
    headers?: Record<string, unknown>;
    parameters?: Record<string, unknown>;
}

export namespace UpdateTool {
    export const Method = {
        Get: "GET",
        Post: "POST",
        Put: "PUT",
        Delete: "DELETE",
        Patch: "PATCH",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
