// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as OrtaVox from "../../../index.js";

export declare namespace CallsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Call management endpoints
 */
export class CallsClient {
    protected readonly _options: CallsClient.Options;

    constructor(options: CallsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Start a web-based voice call with an AI agent
     *
     * @param {OrtaVox.InitiateWebCallCallsRequest} request
     * @param {CallsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.calls.initiateWebCall({
     *         agent_id: "agent_id"
     *     })
     */
    public initiateWebCall(
        request: OrtaVox.InitiateWebCallCallsRequest,
        requestOptions?: CallsClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.InitiateWebCallCallsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__initiateWebCall(request, requestOptions));
    }

    private async __initiateWebCall(
        request: OrtaVox.InitiateWebCallCallsRequest,
        requestOptions?: CallsClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.InitiateWebCallCallsResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/calls/web-call",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OrtaVox.InitiateWebCallCallsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling POST /v1/calls/web-call.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Start an outbound phone call with an AI agent
     *
     * @param {OrtaVox.InitiatePhoneCallCallsRequest} request
     * @param {CallsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.BadRequestError}
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.calls.initiatePhoneCall({
     *         from_number: "+448450950002",
     *         to_number: "+14157774444",
     *         agent_id: "123e4567-e89b-12d3-a456-426614174000"
     *     })
     */
    public initiatePhoneCall(
        request: OrtaVox.InitiatePhoneCallCallsRequest,
        requestOptions?: CallsClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.InitiatePhoneCallCallsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__initiatePhoneCall(request, requestOptions));
    }

    private async __initiatePhoneCall(
        request: OrtaVox.InitiatePhoneCallCallsRequest,
        requestOptions?: CallsClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.InitiatePhoneCallCallsResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/calls/phone-call",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as OrtaVox.InitiatePhoneCallCallsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OrtaVox.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling POST /v1/calls/phone-call.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get all calls for the authenticated user
     *
     * @param {OrtaVox.ListCallsRequest} request
     * @param {CallsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     *
     * @example
     *     await client.calls.list()
     */
    public list(
        request: OrtaVox.ListCallsRequest = {},
        requestOptions?: CallsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: OrtaVox.ListCallsRequest = {},
        requestOptions?: CallsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { status, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (status != null) {
            _queryParams.status = status;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/calls",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling GET /v1/calls.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve detailed information about a specific call
     *
     * @param {OrtaVox.GetCallsRequest} request
     * @param {CallsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.calls.get({
     *         callId: "callId"
     *     })
     */
    public get(
        request: OrtaVox.GetCallsRequest,
        requestOptions?: CallsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: OrtaVox.GetCallsRequest,
        requestOptions?: CallsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { callId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/calls/${core.url.encodePathParam(callId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling GET /v1/calls/{callId}.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
