// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListAgentsRequest {
    /** Maximum number of agents to return per page. */
    limit?: number;
}
