// This file was auto-generated by Fern from our API Definition.

import type * as OrtaVox from "../../../../index.js";

/**
 * @example
 *     {
 *         agentId: "agentId",
 *         body: {
 *             name: "Support Agent",
 *             transcriber: {
 *                 provider: "deepgram",
 *                 model: "nova-3",
 *                 language: "en"
 *             },
 *             model: {
 *                 provider: "openai",
 *                 model: "gpt-4o-mini",
 *                 system_prompt: "You are a helpful AI assistant",
 *                 temperature: 1.1,
 *                 max_tokens: 1.1
 *             },
 *             voice: {
 *                 provider: "elevenlabs",
 *                 voice_id: "dqzVFKHwZvR9YMQoFM67",
 *                 model: "eleven_turbo_v2_5"
 *             }
 *         }
 *     }
 */
export interface UpdateAgentsRequest {
    /** Agent ID */
    agentId: string;
    body: OrtaVox.CreateAgent;
}
