// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumber: "+14157774444"
 *     }
 */
export interface DeleteNumberTelephonyRequest {
    /** Phone number in E.164 format */
    phoneNumber: string;
}
