// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone_number: "+14157774444",
 *         termination_uri: "sip.uk.didlogic.net"
 *     }
 */
export interface ImportNumberTelephonyRequest {
    /** E.164 format phone number */
    phone_number: string;
    /** SIP trunk termination URI */
    termination_uri: string;
    /** Which direction(s) to configure - inbound only, outbound only, or both. Defaults to both if not specified. */
    direction?: ImportNumberTelephonyRequest.Direction;
    /** SIP authentication username (required) */
    sip_auth_username?: string;
    /** SIP authentication password (required) */
    sip_auth_password?: string;
    /** Agent ID for inbound calls */
    inbound_agent_id?: string;
    /** Agent ID for outbound calls */
    outbound_agent_id?: string;
    /** Inbound agent version */
    inbound_agent_version?: number;
    /** Outbound agent version */
    outbound_agent_version?: number;
    /** Friendly name for the phone number */
    nickname?: string;
    /** Webhook URL for inbound call events */
    inbound_webhook_url?: string;
}

export namespace ImportNumberTelephonyRequest {
    /** Which direction(s) to configure - inbound only, outbound only, or both. Defaults to both if not specified. */
    export const Direction = {
        Inbound: "inbound",
        Outbound: "outbound",
        Both: "both",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
}
