// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListNumbersTelephonyRequest {
    /** Number of phone numbers to return per page. */
    limit?: number;
}
