// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumber: "+14157774444"
 *     }
 */
export interface UpdateNumberTelephonyRequest {
    /** Phone number in E.164 format */
    phoneNumber: string;
    inbound_agent_id?: string;
    outbound_agent_id?: string;
    inbound_agent_version?: number;
    outbound_agent_version?: number;
    nickname?: string;
    inbound_webhook_url?: string;
}
