// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as OrtaVox from "../../../index.js";

export declare namespace TelephonyClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Phone number and SIP trunk management
 */
export class TelephonyClient {
    protected readonly _options: TelephonyClient.Options;

    constructor(options: TelephonyClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Import a phone number from custom telephony and bind agents
     *
     * @param {OrtaVox.ImportNumberTelephonyRequest} request
     * @param {TelephonyClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.ConflictError}
     *
     * @example
     *     await client.telephony.importNumber({
     *         phone_number: "+14157774444",
     *         termination_uri: "sip.uk.didlogic.net"
     *     })
     */
    public importNumber(
        request: OrtaVox.ImportNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.ImportNumberTelephonyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__importNumber(request, requestOptions));
    }

    private async __importNumber(
        request: OrtaVox.ImportNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.ImportNumberTelephonyResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/telephony/import",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as OrtaVox.ImportNumberTelephonyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new OrtaVox.ConflictError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling POST /v1/telephony/import.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a list of all phone numbers configured for SIP trunking within your organization, including their bound agents and current authentication state.
     *
     * @param {OrtaVox.ListNumbersTelephonyRequest} request
     * @param {TelephonyClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     *
     * @example
     *     await client.telephony.listNumbers()
     */
    public listNumbers(
        request: OrtaVox.ListNumbersTelephonyRequest = {},
        requestOptions?: TelephonyClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__listNumbers(request, requestOptions));
    }

    private async __listNumbers(
        request: OrtaVox.ListNumbersTelephonyRequest = {},
        requestOptions?: TelephonyClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/telephony/numbers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling GET /v1/telephony/numbers.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve details for a specific phone number
     *
     * @param {OrtaVox.GetNumberTelephonyRequest} request
     * @param {TelephonyClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.telephony.getNumber({
     *         phoneNumber: "+14157774444"
     *     })
     */
    public getNumber(
        request: OrtaVox.GetNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__getNumber(request, requestOptions));
    }

    private async __getNumber(
        request: OrtaVox.GetNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { phoneNumber } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/telephony/numbers/${core.url.encodePathParam(phoneNumber)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError(
                    "Timeout exceeded when calling GET /v1/telephony/numbers/{phoneNumber}.",
                );
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Remove a phone number from the system
     *
     * @param {OrtaVox.DeleteNumberTelephonyRequest} request
     * @param {TelephonyClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.telephony.deleteNumber({
     *         phoneNumber: "+14157774444"
     *     })
     */
    public deleteNumber(
        request: OrtaVox.DeleteNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteNumber(request, requestOptions));
    }

    private async __deleteNumber(
        request: OrtaVox.DeleteNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { phoneNumber } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/telephony/numbers/${core.url.encodePathParam(phoneNumber)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError(
                    "Timeout exceeded when calling DELETE /v1/telephony/numbers/{phoneNumber}.",
                );
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update agent bindings and configuration for a phone number
     *
     * @param {OrtaVox.UpdateNumberTelephonyRequest} request
     * @param {TelephonyClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.UnauthorizedError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.telephony.updateNumber({
     *         phoneNumber: "+14157774444"
     *     })
     */
    public updateNumber(
        request: OrtaVox.UpdateNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__updateNumber(request, requestOptions));
    }

    private async __updateNumber(
        request: OrtaVox.UpdateNumberTelephonyRequest,
        requestOptions?: TelephonyClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { phoneNumber, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/telephony/numbers/${core.url.encodePathParam(phoneNumber)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OrtaVox.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError(
                    "Timeout exceeded when calling PATCH /v1/telephony/numbers/{phoneNumber}.",
                );
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
