// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as OrtaVox from "../../../index.js";

export declare namespace ToolsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Tool management endpoints - Create and manage function tools for agents
 */
export class ToolsClient {
    protected readonly _options: ToolsClient.Options;

    constructor(options: ToolsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * List all tools (end_call and api) for the organization
     *
     * @param {OrtaVox.ListToolsRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tools.list()
     */
    public list(
        request: OrtaVox.ListToolsRequest = {},
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.ListToolsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: OrtaVox.ListToolsRequest = {},
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.ListToolsResponse>> {
        const { type: type_ } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (type_ != null) {
            _queryParams.type = type_;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/tools",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OrtaVox.ListToolsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OrtaVoxError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling GET /v1/tools.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create an end_call or API tool for agents to use
     *
     * @param {OrtaVox.CreateTool} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.BadRequestError}
     *
     * @example
     *     await client.tools.create({
     *         name: "API request",
     *         type: "end_call"
     *     })
     */
    public create(
        request: OrtaVox.CreateTool,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.ToolResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: OrtaVox.CreateTool,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.ToolResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                "v1/tools",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OrtaVox.ToolResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OrtaVox.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling POST /v1/tools.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get details of a specific tool by ID
     *
     * @param {OrtaVox.GetToolsRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.tools.get({
     *         id: "id"
     *     })
     */
    public get(
        request: OrtaVox.GetToolsRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.ToolResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: OrtaVox.GetToolsRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.ToolResponse>> {
        const { id } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/tools/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OrtaVox.ToolResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling GET /v1/tools/{id}.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update a custom tool (cannot update default tools)
     *
     * @param {OrtaVox.UpdateTool} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.BadRequestError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.tools.update({
     *         id: "id"
     *     })
     */
    public update(
        request: OrtaVox.UpdateTool,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<OrtaVox.ToolResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: OrtaVox.UpdateTool,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<OrtaVox.ToolResponse>> {
        const { id, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/tools/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as OrtaVox.ToolResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OrtaVox.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling PUT /v1/tools/{id}.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a custom tool (cannot delete default tools)
     *
     * @param {OrtaVox.DeleteToolsRequest} request
     * @param {ToolsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OrtaVox.BadRequestError}
     * @throws {@link OrtaVox.NotFoundError}
     *
     * @example
     *     await client.tools.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: OrtaVox.DeleteToolsRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: OrtaVox.DeleteToolsRequest,
        requestOptions?: ToolsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { id } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OrtaVoxEnvironment.Default,
                `v1/tools/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OrtaVox.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OrtaVox.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OrtaVoxError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OrtaVoxError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OrtaVoxTimeoutError("Timeout exceeded when calling DELETE /v1/tools/{id}.");
            case "unknown":
                throw new errors.OrtaVoxError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
