// This file was auto-generated by Fern from our API Definition.

export interface AgentResponse {
    data?: AgentResponse.Data;
    meta?: AgentResponse.Meta;
}

export namespace AgentResponse {
    export interface Data {
        id?: string;
        name?: string;
        organizationId?: string;
        configuration?: Data.Configuration;
        createdAt?: string;
        updatedAt?: string;
    }

    export namespace Data {
        export interface Configuration {
            model?: Record<string, unknown>;
            voice?: Record<string, unknown>;
            transcriber?: Record<string, unknown>;
            start_message?: string;
            start_message_mode?: string;
            max_call_duration?: number;
        }
    }

    export interface Meta {
        timestamp?: string;
    }
}
