// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyResponse {
    data?: ApiKeyResponse.Data;
}

export namespace ApiKeyResponse {
    export interface Data {
        id?: string;
        name?: string;
        /** Full key (only shown once on creation) */
        key?: string;
        tag?: Data.Tag;
        restrictions?: Record<string, unknown>;
        permissions?: string[];
        createdAt?: string;
        updatedAt?: string;
    }

    export namespace Data {
        export const Tag = {
            Private: "private",
            Public: "public",
        } as const;
        export type Tag = (typeof Tag)[keyof typeof Tag];
    }
}
