// This file was auto-generated by Fern from our API Definition.

export interface CreateApiKey {
    /** API key name */
    name: string;
    /** Key type: private (sk_live_) or public (pk_live_) */
    tag?: CreateApiKey.Tag;
    restrictions?: CreateApiKey.Restrictions;
    permissions?: string[];
    /** Optional expiration date */
    expiresAt?: string;
}

export namespace CreateApiKey {
    /** Key type: private (sk_live_) or public (pk_live_) */
    export const Tag = {
        Private: "private",
        Public: "public",
    } as const;
    export type Tag = (typeof Tag)[keyof typeof Tag];

    export interface Restrictions {
        /** List of agent IDs this key can access */
        allowedAgentsIds?: string[];
        /** List of allowed origins (for public keys) */
        allowedOrigins?: string[];
    }
}
