// This file was auto-generated by Fern from our API Definition.

export interface CreateAgent {
    /** Agent name */
    name: string;
    transcriber: CreateAgent.Transcriber;
    model: CreateAgent.Model;
    voice: CreateAgent.Voice;
    max_call_duration?: number;
}

export namespace CreateAgent {
    export interface Transcriber {
        provider: Transcriber.Provider;
        model: string;
        language: string;
    }

    export namespace Transcriber {
        export const Provider = {
            Deepgram: "deepgram",
            Openai: "openai",
            Assemblyai: "assemblyai",
            Google: "google",
            Speechmatics: "speechmatics",
            Azure: "azure",
        } as const;
        export type Provider = (typeof Provider)[keyof typeof Provider];
    }

    export interface Model {
        provider: Model.Provider;
        model: string;
        system_prompt: string;
        temperature: number;
        max_tokens: number;
        tools?: unknown[];
    }

    export namespace Model {
        export const Provider = {
            Openai: "openai",
            Anthropic: "anthropic",
            Google: "google",
            Groq: "groq",
            DeepSeek: "deep-seek",
        } as const;
        export type Provider = (typeof Provider)[keyof typeof Provider];
    }

    export interface Voice {
        provider: Voice.Provider;
        voice_id: string;
        model: string;
    }

    export namespace Voice {
        export const Provider = {
            Elevenlabs: "elevenlabs",
            Openai: "openai",
            Google: "google",
            Cartesia: "cartesia",
        } as const;
        export type Provider = (typeof Provider)[keyof typeof Provider];
    }
}
