// This file was auto-generated by Fern from our API Definition.

export interface ImportPhoneNumber {
    /** Phone number in E.164 format */
    phone_number: string;
    /** SIP trunk termination URI */
    termination_uri: string;
    /** SIP trunk authentication username */
    sip_trunk_auth_username?: string;
    /** SIP trunk authentication password */
    sip_trunk_auth_password?: string;
    /** Agent ID for inbound calls */
    inbound_agent_id?: string;
    /** Agent ID for outbound calls */
    outbound_agent_id?: string;
    /** Inbound agent version */
    inbound_agent_version?: number;
    /** Outbound agent version */
    outbound_agent_version?: number;
    /** Friendly name for the phone number */
    nickname?: string;
    /** Webhook URL for inbound call events */
    inbound_webhook_url?: string;
}
