// This file was auto-generated by Fern from our API Definition.

export interface PhoneNumberResponse {
    phone_number?: string;
    phone_number_type?: string;
    phone_number_pretty?: string;
    inbound_agent_id?: string | null;
    outbound_agent_id?: string | null;
    inbound_agent_version?: number | null;
    outbound_agent_version?: number | null;
    area_code?: number | null;
    nickname?: string | null;
    inbound_webhook_url?: string | null;
    last_modification_timestamp?: number;
}
