// This file was auto-generated by Fern from our API Definition.

export interface ToolResponse {
    data?: ToolResponse.Data;
}

export namespace ToolResponse {
    export interface Data {
        id?: string;
        type?: Data.Type;
        createdAt?: string;
        updatedAt?: string;
        tool?: Data.Tool;
    }

    export namespace Data {
        export const Type = {
            EndCall: "end_call",
            Api: "api",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];

        export interface Tool {
            type?: Tool.Type;
            name?: string;
            description?: string;
            parameters?: Record<string, unknown> | null;
            url?: string | null;
            method?: string | null;
            headers?: Record<string, unknown> | null;
            goodbye_message?: string | null;
        }

        export namespace Tool {
            export const Type = {
                EndCall: "end_call",
                Api: "api",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }
}
