// This file was auto-generated by Fern from our API Definition.

export const ListToolsRequestType = {
    EndCall: "end_call",
    Api: "api",
} as const;
export type ListToolsRequestType = (typeof ListToolsRequestType)[keyof typeof ListToolsRequestType];
