// This file was auto-generated by Fern from our API Definition.

export interface InitiateWebCallCallsResponse {
    data?: InitiateWebCallCallsResponse.Data;
}

export namespace InitiateWebCallCallsResponse {
    export interface Data {
        callId?: string;
        roomName?: string;
        token?: string;
    }
}
