// This file was auto-generated by Fern from our API Definition.

export interface InitiatePhoneCallCallsResponse {
    data?: InitiatePhoneCallCallsResponse.Data;
}

export namespace InitiatePhoneCallCallsResponse {
    export interface Data {
        callId?: string;
        roomName?: string;
        conversationId?: string;
        status?: Data.Status;
        livekitUrl?: string;
        createdAt?: string;
    }

    export namespace Data {
        export const Status = {
            Initiated: "initiated",
            Connecting: "connecting",
            Active: "active",
            Completed: "completed",
            Failed: "failed",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
