// This file was auto-generated by Fern from our API Definition.

export const ListCallsRequestStatus = {
    Queued: "queued",
    Ringing: "ringing",
    InProgress: "in-progress",
    Completed: "completed",
    Failed: "failed",
    Busy: "busy",
    NoAnswer: "no-answer",
} as const;
export type ListCallsRequestStatus = (typeof ListCallsRequestStatus)[keyof typeof ListCallsRequestStatus];
