// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_id: "agent_id"
 *     }
 */
export interface InitiateWebCallCallsRequest {
    /** UUID of the agent to use for the call */
    agent_id: string;
    /** Optional metadata for the call */
    metadata?: InitiateWebCallCallsRequest.Metadata;
}

export namespace InitiateWebCallCallsRequest {
    /**
     * Optional metadata for the call
     */
    export interface Metadata {
        /** Custom name for the assistant */
        assistantName?: string;
        /** Custom system prompt */
        systemPrompt?: string;
        /** Initial message from the agent */
        startMessage?: string;
        /** Background sound URL */
        backgroundSound?: string;
    }
}
