// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         from_number: "+448450950002",
 *         to_number: "+14157774444",
 *         agent_id: "123e4567-e89b-12d3-a456-426614174000"
 *     }
 */
export interface InitiatePhoneCallCallsRequest {
    /** Phone number to call from (E.164 format) - must be a registered phone number */
    from_number: string;
    /** Phone number to call to (E.164 format) */
    to_number: string;
    /** ID of the agent to use for the call */
    agent_id: string;
    /** Optional dynamic variables to pass to the agent (key-value pairs) */
    dynamic_variables?: Record<string, unknown>;
}
