// This file was auto-generated by Fern from our API Definition.

import type * as OrtaVox from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListCallsRequest {
    /** Filter calls by their specific lifecycle status. Useful for polling active calls. */
    status?: OrtaVox.ListCallsRequestStatus;
    /** Maximum number of calls to return for pagination purposes. */
    limit?: number;
}
