// This file was auto-generated by Fern from our API Definition.

import * as OrtaVox from "../../src/api/index";
import { OrtaVoxClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/v1/agents").respondWith().statusCode(200).build();

        const response = await client.agents.list();
        expect(response).toEqual(undefined);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Support Agent",
            transcriber: { provider: "deepgram", model: "nova-3", language: "en" },
            model: {
                provider: "openai",
                model: "gpt-4o-mini",
                system_prompt: "You are a helpful AI assistant",
                temperature: 1.1,
                max_tokens: 1.1,
            },
            voice: { provider: "elevenlabs", voice_id: "dqzVFKHwZvR9YMQoFM67", model: "eleven_turbo_v2_5" },
        };
        const rawResponseBody = {
            data: {
                id: "id",
                name: "name",
                organizationId: "organizationId",
                configuration: {
                    model: { key: "value" },
                    voice: { key: "value" },
                    transcriber: { key: "value" },
                    start_message: "start_message",
                    start_message_mode: "start_message_mode",
                    max_call_duration: 1.1,
                },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            meta: { timestamp: "timestamp" },
        };
        server
            .mockEndpoint()
            .post("/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.create({
            name: "Support Agent",
            transcriber: {
                provider: "deepgram",
                model: "nova-3",
                language: "en",
            },
            model: {
                provider: "openai",
                model: "gpt-4o-mini",
                system_prompt: "You are a helpful AI assistant",
                temperature: 1.1,
                max_tokens: 1.1,
            },
            voice: {
                provider: "elevenlabs",
                voice_id: "dqzVFKHwZvR9YMQoFM67",
                model: "eleven_turbo_v2_5",
            },
        });
        expect(response).toEqual({
            data: {
                id: "id",
                name: "name",
                organizationId: "organizationId",
                configuration: {
                    model: {
                        key: "value",
                    },
                    voice: {
                        key: "value",
                    },
                    transcriber: {
                        key: "value",
                    },
                    start_message: "start_message",
                    start_message_mode: "start_message_mode",
                    max_call_duration: 1.1,
                },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            meta: {
                timestamp: "timestamp",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            transcriber: { provider: "deepgram", model: "model", language: "en" },
            model: {
                provider: "openai",
                model: "model",
                system_prompt: "system_prompt",
                temperature: 2,
                max_tokens: 1.1,
            },
            voice: { provider: "elevenlabs", voice_id: "voice_id", model: "model" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "name",
                transcriber: {
                    provider: "deepgram",
                    model: "model",
                    language: "en",
                },
                model: {
                    provider: "openai",
                    model: "model",
                    system_prompt: "system_prompt",
                    temperature: 2,
                    max_tokens: 1.1,
                },
                voice: {
                    provider: "elevenlabs",
                    voice_id: "voice_id",
                    model: "model",
                },
            });
        }).rejects.toThrow(OrtaVox.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            transcriber: { provider: "deepgram", model: "model", language: "en" },
            model: {
                provider: "openai",
                model: "model",
                system_prompt: "system_prompt",
                temperature: 2,
                max_tokens: 1.1,
            },
            voice: { provider: "elevenlabs", voice_id: "voice_id", model: "model" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "name",
                transcriber: {
                    provider: "deepgram",
                    model: "model",
                    language: "en",
                },
                model: {
                    provider: "openai",
                    model: "model",
                    system_prompt: "system_prompt",
                    temperature: 2,
                    max_tokens: 1.1,
                },
                voice: {
                    provider: "elevenlabs",
                    voice_id: "voice_id",
                    model: "model",
                },
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/v1/agents/agentId").respondWith().statusCode(200).build();

        const response = await client.agents.get({
            agentId: "agentId",
        });
        expect(response).toEqual(undefined);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/agents/agentId").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.get({
                agentId: "agentId",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/agents/agentId").respondWith().statusCode(200).build();

        const response = await client.agents.delete({
            agentId: "agentId",
        });
        expect(response).toEqual(undefined);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Support Agent",
            transcriber: { provider: "deepgram", model: "nova-3", language: "en" },
            model: {
                provider: "openai",
                model: "gpt-4o-mini",
                system_prompt: "You are a helpful AI assistant",
                temperature: 1.1,
                max_tokens: 1.1,
            },
            voice: { provider: "elevenlabs", voice_id: "dqzVFKHwZvR9YMQoFM67", model: "eleven_turbo_v2_5" },
        };

        server
            .mockEndpoint()
            .patch("/v1/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.agents.update({
            agentId: "agentId",
            body: {
                name: "Support Agent",
                transcriber: {
                    provider: "deepgram",
                    model: "nova-3",
                    language: "en",
                },
                model: {
                    provider: "openai",
                    model: "gpt-4o-mini",
                    system_prompt: "You are a helpful AI assistant",
                    temperature: 1.1,
                    max_tokens: 1.1,
                },
                voice: {
                    provider: "elevenlabs",
                    voice_id: "dqzVFKHwZvR9YMQoFM67",
                    model: "eleven_turbo_v2_5",
                },
            },
        });
        expect(response).toEqual(undefined);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            transcriber: { provider: "deepgram", model: "model", language: "en" },
            model: {
                provider: "openai",
                model: "model",
                system_prompt: "system_prompt",
                temperature: 2,
                max_tokens: 1.1,
            },
            voice: { provider: "elevenlabs", voice_id: "voice_id", model: "model" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update({
                agentId: "agentId",
                body: {
                    name: "name",
                    transcriber: {
                        provider: "deepgram",
                        model: "model",
                        language: "en",
                    },
                    model: {
                        provider: "openai",
                        model: "model",
                        system_prompt: "system_prompt",
                        temperature: 2,
                        max_tokens: 1.1,
                    },
                    voice: {
                        provider: "elevenlabs",
                        voice_id: "voice_id",
                        model: "model",
                    },
                },
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            transcriber: { provider: "deepgram", model: "model", language: "en" },
            model: {
                provider: "openai",
                model: "model",
                system_prompt: "system_prompt",
                temperature: 2,
                max_tokens: 1.1,
            },
            voice: { provider: "elevenlabs", voice_id: "voice_id", model: "model" },
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.update({
                agentId: "agentId",
                body: {
                    name: "name",
                    transcriber: {
                        provider: "deepgram",
                        model: "model",
                        language: "en",
                    },
                    model: {
                        provider: "openai",
                        model: "model",
                        system_prompt: "system_prompt",
                        temperature: 2,
                        max_tokens: 1.1,
                    },
                    voice: {
                        provider: "elevenlabs",
                        voice_id: "voice_id",
                        model: "model",
                    },
                },
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });
});
