// This file was auto-generated by Fern from our API Definition.

import * as OrtaVox from "../../src/api/index";
import { OrtaVoxClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CallsClient", () => {
    test("initiateWebCall (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id" };
        const rawResponseBody = { data: { callId: "callId", roomName: "roomName", token: "token" } };
        server
            .mockEndpoint()
            .post("/v1/calls/web-call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.initiateWebCall({
            agent_id: "agent_id",
        });
        expect(response).toEqual({
            data: {
                callId: "callId",
                roomName: "roomName",
                token: "token",
            },
        });
    });

    test("initiateWebCall (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/calls/web-call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.initiateWebCall({
                agent_id: "agent_id",
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("initiateWebCall (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_id: "agent_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/calls/web-call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.initiateWebCall({
                agent_id: "agent_id",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });

    test("initiatePhoneCall (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            from_number: "+448450950002",
            to_number: "+14157774444",
            agent_id: "123e4567-e89b-12d3-a456-426614174000",
        };
        const rawResponseBody = {
            data: {
                callId: "callId",
                roomName: "roomName",
                conversationId: "conversationId",
                status: "initiated",
                livekitUrl: "livekitUrl",
                createdAt: "2024-01-15T09:30:00Z",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/calls/phone-call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.calls.initiatePhoneCall({
            from_number: "+448450950002",
            to_number: "+14157774444",
            agent_id: "123e4567-e89b-12d3-a456-426614174000",
        });
        expect(response).toEqual({
            data: {
                callId: "callId",
                roomName: "roomName",
                conversationId: "conversationId",
                status: "initiated",
                livekitUrl: "livekitUrl",
                createdAt: "2024-01-15T09:30:00Z",
            },
        });
    });

    test("initiatePhoneCall (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from_number: "from_number", to_number: "to_number", agent_id: "agent_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/calls/phone-call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.initiatePhoneCall({
                from_number: "from_number",
                to_number: "to_number",
                agent_id: "agent_id",
            });
        }).rejects.toThrow(OrtaVox.BadRequestError);
    });

    test("initiatePhoneCall (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from_number: "from_number", to_number: "to_number", agent_id: "agent_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/calls/phone-call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.initiatePhoneCall({
                from_number: "from_number",
                to_number: "to_number",
                agent_id: "agent_id",
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("initiatePhoneCall (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { from_number: "from_number", to_number: "to_number", agent_id: "agent_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/calls/phone-call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.calls.initiatePhoneCall({
                from_number: "from_number",
                to_number: "to_number",
                agent_id: "agent_id",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/v1/calls").respondWith().statusCode(200).build();

        const response = await client.calls.list();
        expect(response).toEqual(undefined);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/calls").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.list();
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/v1/calls/callId").respondWith().statusCode(200).build();

        const response = await client.calls.get({
            callId: "callId",
        });
        expect(response).toEqual(undefined);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/calls/callId").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.get({
                callId: "callId",
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/calls/callId").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.calls.get({
                callId: "callId",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });
});
