// This file was auto-generated by Fern from our API Definition.

import * as OrtaVox from "../../src/api/index";
import { OrtaVoxClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TelephonyClient", () => {
    test("importNumber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { phone_number: "+14157774444", termination_uri: "sip.uk.didlogic.net" };
        const rawResponseBody = {
            data: {
                phone_number: "phone_number",
                inbound_sip_trunk_id: "inbound_sip_trunk_id",
                outbound_sip_trunk_id: "outbound_sip_trunk_id",
                auth_state: "authenticated",
                auth_state_message: "auth_state_message",
            },
        };
        server
            .mockEndpoint()
            .post("/v1/telephony/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.importNumber({
            phone_number: "+14157774444",
            termination_uri: "sip.uk.didlogic.net",
        });
        expect(response).toEqual({
            data: {
                phone_number: "phone_number",
                inbound_sip_trunk_id: "inbound_sip_trunk_id",
                outbound_sip_trunk_id: "outbound_sip_trunk_id",
                auth_state: "authenticated",
                auth_state_message: "auth_state_message",
            },
        });
    });

    test("importNumber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { phone_number: "phone_number", termination_uri: "termination_uri" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/telephony/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.importNumber({
                phone_number: "phone_number",
                termination_uri: "termination_uri",
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("importNumber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { phone_number: "phone_number", termination_uri: "termination_uri" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/telephony/import")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.importNumber({
                phone_number: "phone_number",
                termination_uri: "termination_uri",
            });
        }).rejects.toThrow(OrtaVox.ConflictError);
    });

    test("listNumbers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/v1/telephony/numbers").respondWith().statusCode(200).build();

        const response = await client.telephony.listNumbers();
        expect(response).toEqual(undefined);
    });

    test("listNumbers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/telephony/numbers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.listNumbers();
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("getNumber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().get("/v1/telephony/numbers/%2B14157774444").respondWith().statusCode(200).build();

        const response = await client.telephony.getNumber({
            phoneNumber: "+14157774444",
        });
        expect(response).toEqual(undefined);
    });

    test("getNumber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/telephony/numbers/phoneNumber")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.getNumber({
                phoneNumber: "phoneNumber",
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("getNumber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/telephony/numbers/phoneNumber")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.getNumber({
                phoneNumber: "phoneNumber",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });

    test("deleteNumber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/telephony/numbers/%2B14157774444").respondWith().statusCode(200).build();

        const response = await client.telephony.deleteNumber({
            phoneNumber: "+14157774444",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteNumber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/telephony/numbers/phoneNumber")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.deleteNumber({
                phoneNumber: "phoneNumber",
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("deleteNumber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/v1/telephony/numbers/phoneNumber")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.deleteNumber({
                phoneNumber: "phoneNumber",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });

    test("updateNumber (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};

        server
            .mockEndpoint()
            .patch("/v1/telephony/numbers/%2B14157774444")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.telephony.updateNumber({
            phoneNumber: "+14157774444",
        });
        expect(response).toEqual(undefined);
    });

    test("updateNumber (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/telephony/numbers/phoneNumber")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.updateNumber({
                phoneNumber: "phoneNumber",
            });
        }).rejects.toThrow(OrtaVox.UnauthorizedError);
    });

    test("updateNumber (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/v1/telephony/numbers/phoneNumber")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.telephony.updateNumber({
                phoneNumber: "phoneNumber",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });
});
