// This file was auto-generated by Fern from our API Definition.

import * as OrtaVox from "../../src/api/index";
import { OrtaVoxClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ToolsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: [{}] };
        server.mockEndpoint().get("/v1/tools").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tools.list();
        expect(response).toEqual({
            data: [{}],
        });
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "API request", type: "end_call" };
        const rawResponseBody = {
            data: {
                id: "id",
                type: "end_call",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                tool: {
                    type: "end_call",
                    name: "name",
                    description: "description",
                    parameters: { key: "value" },
                    url: "url",
                    method: "method",
                    headers: { key: "value" },
                    goodbye_message: "goodbye_message",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/v1/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.create({
            name: "API request",
            type: "end_call",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                type: "end_call",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                tool: {
                    type: "end_call",
                    name: "name",
                    description: "description",
                    parameters: {
                        key: "value",
                    },
                    url: "url",
                    method: "method",
                    headers: {
                        key: "value",
                    },
                    goodbye_message: "goodbye_message",
                },
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", type: "end_call" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.create({
                name: "name",
                type: "end_call",
            });
        }).rejects.toThrow(OrtaVox.BadRequestError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                type: "end_call",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                tool: {
                    type: "end_call",
                    name: "name",
                    description: "description",
                    parameters: { key: "value" },
                    url: "url",
                    method: "method",
                    headers: { key: "value" },
                    goodbye_message: "goodbye_message",
                },
            },
        };
        server.mockEndpoint().get("/v1/tools/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tools.get({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                type: "end_call",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                tool: {
                    type: "end_call",
                    name: "name",
                    description: "description",
                    parameters: {
                        key: "value",
                    },
                    url: "url",
                    method: "method",
                    headers: {
                        key: "value",
                    },
                    goodbye_message: "goodbye_message",
                },
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/v1/tools/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tools.get({
                id: "id",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                type: "end_call",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                tool: {
                    type: "end_call",
                    name: "name",
                    description: "description",
                    parameters: { key: "value" },
                    url: "url",
                    method: "method",
                    headers: { key: "value" },
                    goodbye_message: "goodbye_message",
                },
            },
        };
        server
            .mockEndpoint()
            .put("/v1/tools/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tools.update({
            id: "id",
        });
        expect(response).toEqual({
            data: {
                id: "id",
                type: "end_call",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                tool: {
                    type: "end_call",
                    name: "name",
                    description: "description",
                    parameters: {
                        key: "value",
                    },
                    url: "url",
                    method: "method",
                    headers: {
                        key: "value",
                    },
                    goodbye_message: "goodbye_message",
                },
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/v1/tools/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.update({
                id: "id",
            });
        }).rejects.toThrow(OrtaVox.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/v1/tools/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tools.update({
                id: "id",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v1/tools/id").respondWith().statusCode(200).build();

        const response = await client.tools.delete({
            id: "id",
        });
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/v1/tools/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tools.delete({
                id: "id",
            });
        }).rejects.toThrow(OrtaVox.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new OrtaVoxClient({ maxRetries: 0, token: "test", apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/v1/tools/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tools.delete({
                id: "id",
            });
        }).rejects.toThrow(OrtaVox.NotFoundError);
    });
});
