// This file was auto-generated by Fern from our API Definition.

export interface ImportNumberTelephonyResponse {
    data?: ImportNumberTelephonyResponse.Data;
}

export namespace ImportNumberTelephonyResponse {
    export interface Data {
        phone_number?: string;
        inbound_sip_trunk_id?: string | null;
        outbound_sip_trunk_id?: string | null;
        auth_state?: Data.AuthState;
        auth_state_message?: string | null;
    }

    export namespace Data {
        export const AuthState = {
            Authenticated: "authenticated",
            NotAuthenticated: "not_authenticated",
            ServerError: "server_error",
            NotVerified: "not_verified",
        } as const;
        export type AuthState = (typeof AuthState)[keyof typeof AuthState];
    }
}
