// This file was auto-generated by Fern from our API Definition.

import { AgentsClient } from "./api/resources/agents/client/Client.js";
import { CallsClient } from "./api/resources/calls/client/Client.js";
import { TelephonyClient } from "./api/resources/telephony/client/Client.js";
import { ToolsClient } from "./api/resources/tools/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace OrtaVoxClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class OrtaVoxClient {
    protected readonly _options: OrtaVoxClient.Options;
    protected _agents: AgentsClient | undefined;
    protected _calls: CallsClient | undefined;
    protected _telephony: TelephonyClient | undefined;
    protected _tools: ToolsClient | undefined;

    constructor(options: OrtaVoxClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get agents(): AgentsClient {
        return (this._agents ??= new AgentsClient(this._options));
    }

    public get calls(): CallsClient {
        return (this._calls ??= new CallsClient(this._options));
    }

    public get telephony(): TelephonyClient {
        return (this._telephony ??= new TelephonyClient(this._options));
    }

    public get tools(): ToolsClient {
        return (this._tools ??= new ToolsClient(this._options));
    }
}
