// This file was auto-generated by Fern from our API Definition.

export const OrtaVoxEnvironment = {
    Default: "https://api.ortavox.ai",
} as const;

export type OrtaVoxEnvironment = typeof OrtaVoxEnvironment.Default;
